export type LocationType = "farm" | "vineyard" | "beekeeping" | "park" | "lakeside" | "citrus" | "animal" | "cultural" | "tea";

export interface Location {
  id: string;
  name: string;
  type: LocationType;
  region: string;
  village: string;
  lat: number;
  lng: number;
  description: string;
  activities: string[];
  products: string[];
  visitInfo: string;
  contact?: string;
  emoji: string;
  color: string;
  photos: { url: string; caption: string }[];
}

export const TYPE_META: Record<LocationType, { label: string; emoji: string; color: string }> = {
  farm:       { label: "Aqroturizm",       emoji: "🌾", color: "#7A8B5C" },
  vineyard:   { label: "Üzümlük",          emoji: "🍇", color: "#9B59B6" },
  beekeeping: { label: "Arıçılıq",         emoji: "🐝", color: "#E8B547" },
  park:       { label: "Milli Park",       emoji: "🌲", color: "#2ECC71" },
  lakeside:   { label: "Göl & Kamp",       emoji: "🏕️", color: "#3498DB" },
  citrus:     { label: "Sitrus Bağı",      emoji: "🍋", color: "#F39C12" },
  animal:     { label: "Heyvan Ferması",   emoji: "🦙", color: "#E74C3C" },
  cultural:   { label: "Kənd Turizmi",    emoji: "🏺", color: "#C0392B" },
  tea:        { label: "Çay Plantasiyası", emoji: "🍵", color: "#27AE60" },
};

export const LOCATIONS: Location[] = [
  {
    id: "biogarden",
    name: "BioGarden",
    type: "farm",
    region: "Şəki",
    village: "Oryat kəndi",
    lat: 41.182,
    lng: 47.108,
    description: "8 hektarlıq üzvi bağ, 3000 meyvə ağacı, ekzotik quşlar, yerli heyvanlar, arıçılıq, üzvi restoran, süni göllər və üzvi bazar — Şəkinin ən unikal aqroturizm məkanı.",
    activities: ["Meyvə yığımı", "Arıçılıq dərsi", "Üzvi restoran", "Heyvanlarla tanışlıq", "Göldə balıqçılıq", "Üzvi bazar"],
    products: ["Üzvi meyvə", "Yerli bal", "Bostanmeyvəsi", "Nar suyu"],
    visitInfo: "Hər gün 09:00 – 19:00",
    contact: "+994 55 XXX XX XX",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "https://biogardensheki.az/images/flora_fauna.jpg",       caption: "BioGarden — flora və fauna, Oryat kəndi, Şəki" },
      { url: "https://biogardensheki.az/upload/202406183209.jpg",       caption: "Meyvə bağları və yaşıl ərazilər" },
      { url: "https://biogardensheki.az/upload/202406192038.jpg",       caption: "Üzvi bağ — 8 hektar sahə" },
      { url: "https://biogardensheki.az/upload/202406194700.jpg",       caption: "Süni göl və istirahət zonaları" },
      { url: "https://biogardensheki.az/upload/202310235311.jpg",       caption: "Yerli heyvanlar və ekzotik quşlar" },
    ],
  },
  {
    id: "hirkan",
    name: "Hirkan Milli Parkı",
    type: "park",
    region: "Lənkəran / Astara",
    village: "Lənkəran",
    lat: 38.784,
    lng: 48.567,
    description: "Nadir bitki örtüyü, Talış dağları, zəngin vəhşi təbiət. Azərbaycanın cənubunda yerləşən UNESCO miras meşəsi — qisman tropik iqlim və endemik flora.",
    activities: ["Piyada turizm", "Eko-turizm", "Quş müşahidəsi", "Fotoqrafiya"],
    products: ["Şəkər qamışı", "Lotan palması", "Dərman bitkiləri"],
    visitInfo: "Hər gün 08:00 – 18:00",
    emoji: "🌲",
    color: "#2ECC71",
    photos: [
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-3.jpeg",                                             caption: "Hirkan Milli Parkı — sıx meşə örtüyü" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-lankaran-2.jpg",                                     caption: "Hirkan meşəsi, Lənkəran — UNESCO Dünya Mirası" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-travel-azerbaijan-lankaran-natura-astara-1.jpg",     caption: "Talış dağlarının ətəyi — endemik flora" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-travel-lankaran-1.jpeg",                             caption: "Piyada turizm marşrutu, Astara" },
    ],
  },
  {
    id: "citrus",
    name: "Sitrus Vadisi",
    type: "citrus",
    region: "Lənkəran",
    village: "İstisu qəsəbəsi",
    lat: 38.808,
    lng: 48.594,
    description: "Lənkəranın münbit subtropik iqlimindəki sitrus bağları — mandarin, limon, portağal. Yerli kəndlilərlə birlikdə yığım təcrübəsi.",
    activities: ["Sitrus yığımı", "Bağ gəzintisi", "Yerli bazar"],
    products: ["Mandarin", "Limon", "Portağal", "Feijoa"],
    visitInfo: "Noyabr – Yanvar (hasat mövsümü)",
    emoji: "🍋",
    color: "#F39C12",
    photos: [
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-tour-azerbaijan.jpg",          caption: "Sitrus Vadisi — Lənkəran subtropik bağları" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-azerbaijan-tour-lankaran.jpg",  caption: "Mandarin bağları — İstisu qəsəbəsi" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-tour-azerbaijan-lankaran.jpg",  caption: "Aqroturizm təcrübəsi — meyvə yığımı" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-lankaran-tour-azerbaijan.jpg",  caption: "Yerli sitrus məhsulları bazarı" },
    ],
  },
  {
    id: "ugur",
    name: "Uğur Aqroturizm",
    type: "farm",
    region: "Masallı",
    village: "Tükla kəndi",
    lat: 39.018,
    lng: 48.674,
    description: "Masallının səfalı kəndlərində ənənəvi kənd həyatı, üzvi ferma məhsulları və yerli mətbəxi ilə tanışlıq.",
    activities: ["Kənd turları", "Üzvi ferma", "Yerli mətbəx dərsi", "Heyvanlarla tanışlıq"],
    products: ["Kənd yumurtası", "Ev pendiri", "Tərəvəz"],
    visitInfo: "Həftə içi 09:00 – 17:00",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "https://lookaside.instagram.com/seo/google_widget/crawler/?media_id=3436833034063915927", caption: "Uğur Aqroturizm — Tükla kəndi, Masallı" },
      { url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=900&q=85&fit=crop",       caption: "Ənənəvi ferma — yerli heyvanlar" },
      { url: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=900&q=85&fit=crop",       caption: "Üzvi tərəvəz bağçası" },
      { url: "https://images.unsplash.com/photo-1542223616-9de9adb5e3e8?w=900&q=85&fit=crop",         caption: "Kənd həyatı — yerli mətbəx" },
    ],
  },
  {
    id: "honey",
    name: "Honey Garden",
    type: "beekeeping",
    region: "Şamaxı",
    village: "Qaladərəsi kəndi",
    lat: 40.658,
    lng: 48.776,
    description: "Şamaxı dağlarında yerli arıçılıq ənənəsi. Bal istehsalı prosesi, arı ailələri ilə tanışlıq və praktik arıçılıq dərsləri.",
    activities: ["Arıçılıq dərsi", "Bal dadımı", "Arı ailəsi müşahidəsi", "Mum şam düzəltmə"],
    products: ["Dağ balı", "Şan balı", "Propolis", "Arı südü"],
    visitInfo: "Aprel – Oktyabr, hər gün 10:00 – 17:00",
    emoji: "🐝",
    color: "#E8B547",
    photos: [
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoc2OyfYUVxauSHbKv_0khFdhpMQfdqujh_g&s",         caption: "Honey Garden — Qaladərəsi kəndi, Şamaxı" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH5vc6JuWZrOtKah-v-RpRH-Qv_hYe-andwux1fuZ8nQ&s", caption: "Şan balı — Şamaxı dağ çiçəklərindən" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZfOda4xgAs5H8WFysBch02elGYw8Q7dbQ16vPiJ5ZoI8ZP7xrBKCpFNk&s", caption: "Arı ailəsi ilə praktik arıçılıq" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx4e9pjNxN4fFmKikb-5zBJjmwJLitgIGkhvous4-xDQ&s",  caption: "Yerli bal məhsulları — dequstasiya" },
    ],
  },
  {
    id: "lakeside",
    name: "Lakeside Garden",
    type: "lakeside",
    region: "İsmayıllı",
    village: "Tazakənd kəndi",
    lat: 40.803,
    lng: 48.133,
    description: "Göl kənarında üzvi ferma, kamp sahəsi, kənd həyatı və sakit təbiət. Ailəvi istirahət üçün mükəmməl məkan.",
    activities: ["Kamp", "Balıqçılıq", "Kayak", "Üzvi bağçılıq", "Kənd gəzintisi"],
    products: ["Üzvi tərəvəz", "Meyvə", "Yerli qozlar"],
    visitInfo: "Hər gün 08:00 – 21:00",
    emoji: "🏕️",
    color: "#3498DB",
    photos: [
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/a97c51a1-0c20-41b7-9c9e-6c362120c2b7.jpg", caption: "Lakeside Garden — Tazakənd, İsmayıllı" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/a62bce82-9a73-4035-bf40-68e6482f6fb2.JPG", caption: "Göl kənarı istirahət ərazisi" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/0f97d3f5-2ec9-47fa-8e70-155b2a69ffb0.jpeg", caption: "Kamp sahəsi — üzvi ferma bağçası" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/cd075042-1a55-48d2-9fbb-dcfed6e06e99.JPG", caption: "Göl mənzərəsi — dağ havası" },
    ],
  },
  {
    id: "meysari",
    name: "Meysari Şərabxanası",
    type: "vineyard",
    region: "Şamaxı",
    village: "Meysari kəndi",
    lat: 40.688,
    lng: 48.622,
    description: "Şamaxı torpağının qədim üzüm sortlarından hazırlanan üzvi şərablar. Üzümlük turları, şərab dadımı və restoran təcrübəsi.",
    activities: ["Üzümlük turu", "Şərab dadımı", "Üzüm yığımı", "Restoran", "Cellar turu"],
    products: ["Üzvi şərab", "Üzüm suyu", "Konyak", "Üzüm sirkəsi"],
    visitInfo: "Çərşənbə – Bazar 10:00 – 19:00",
    contact: "+994 50 XXX XX XX",
    emoji: "🍇",
    color: "#9B59B6",
    photos: [
      { url: "https://meysariwines.az/media/img/winery/winery_1_1.png",  caption: "Meysari Şərabxanası — Şamaxı" },
      { url: "https://meysariwines.az/media/img/winery/winery3_1.png",   caption: "Üzümlük — qədim Şamaxı torpağı" },
      { url: "https://meysariwines.az/media/img/winery/winery_6.png",    caption: "Şərab istehsal prosesi" },
      { url: "https://meysariwines.az/media/img/history/history6_1.png", caption: "Meysari şərab tarixi" },
    ],
  },
  {
    id: "alpaca",
    name: "Şamaxı Alpaka Ferması",
    type: "animal",
    region: "Şamaxı",
    village: "Şamaxı",
    lat: 40.617,
    lng: 48.641,
    description: "Azərbaycanda yeganə alpaka ferması. Ailə turizmi, piknik əraziləri və uşaqlar üçün əyləncəli heyvan tanışlığı.",
    activities: ["Alpaka ilə tanışlıq", "Piknik", "Fotoqrafiya", "Uşaq proqramları", "Heyvan bəsləmə"],
    products: ["Alpaka yunu", "Əl işi məmulatlar"],
    visitInfo: "Həftə sonu 10:00 – 18:00, həftə içi rezervasiya ilə",
    emoji: "🦙",
    color: "#E74C3C",
    photos: [
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/e7/89/6e/main-pasture.jpg?w=1400&h=800&s=1",     caption: "Şamaxı Alpaka Ferması — əsas otlaq sahəsi" },
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/f0/48/49/alpaca-azerbaijan.jpg?w=1100&h=-1&s=1",  caption: "Alpaka Azerbaijan — yaxın tanışlıq" },
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/e7/5d/7a/caption.jpg?w=1400&h=-1&s=1",            caption: "Ailə turizmi — piknik əraziləri" },
    ],
  },
  {
    id: "teafarm",
    name: "Yaşıl Çay Plantasiyası",
    type: "tea",
    region: "Lənkəran",
    village: "Lənkəran",
    lat: 38.750,
    lng: 48.848,
    description: "Azərbaycanın cənub subtropik qurşağında yerləşən çay bağları. Çay yığımı, emal prosesi və yerli aqrar ənənələrlə tanışlıq.",
    activities: ["Çay yığımı", "Emal prosesi izlənməsi", "Çay dadımı", "Plantasiya turu"],
    products: ["Yaşıl çay", "Qara çay", "Çay ekstraktı"],
    visitInfo: "May – Sentyabr 08:00 – 17:00",
    emoji: "🍵",
    color: "#27AE60",
    photos: [
      {
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/%C4%B0lham_%C6%8Fliyev_L%C9%99nk%C9%99randa_%E2%80%9CYa%C5%9F%C4%B1l_%C3%87ay%E2%80%9D_plantasiyas%C4%B1_il%C9%99_tan%C4%B1%C5%9F_olark%C9%99n_17.jpg/1920px-%C4%B0lham_%C6%8Fliyev_L%C9%99nk%C9%99randa_%E2%80%9CYa%C5%9F%C4%B1l_%C3%87ay%E2%80%9D_plantasiyas%C4%B1_il%C9%99_tan%C4%B1%C5%9F_olark%C9%99n_17.jpg",
        caption: "Yaşıl Çay Plantasiyası — Lənkəran",
      },
      { url: "https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?w=900&q=85&fit=crop", caption: "Sıra ilə çay kolları — subtropik iqlim" },
      { url: "https://images.unsplash.com/photo-1558981852-426c537b64c0?w=900&q=85&fit=crop",   caption: "Əl ilə çay yığımı mövsümü" },
      { url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=900&q=85&fit=crop",   caption: "Yerli çay dadımı — Lənkəran" },
    ],
  },
  {
    id: "lahij",
    name: "Lahıc Kəndi",
    type: "cultural",
    region: "İsmayıllı",
    village: "Lahıc kəndi",
    lat: 40.847,
    lng: 48.335,
    description: "Qafqazın ən qədim qəsəbələrindən biri. Mis sənətkarlığı, tarixi memarlıq, dağ kəndi atmosferi və ənənəvi əl işləri.",
    activities: ["Mis emalatxanası turu", "Tarixi gəzinti", "Sənətkarlıq dərsi", "Fotoqrafiya"],
    products: ["Mis qab-qacaq", "Ənənəvi silah", "Zınqıllar", "Keramika"],
    visitInfo: "Hər gün 09:00 – 18:00",
    emoji: "🏺",
    color: "#C0392B",
    photos: [
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Lahic_kollaj.jpg/960px-Lahic_kollaj.jpg", caption: "Lahıc kəndi — kollaj, İsmayıllı" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSUIQcrq76yUv33jajNCyODFd8g_q74emRHKOhxGZ_ad_D1Nnh2QqwBBStXLH4qGxMSOVBblag5REap9fb00S08nlw&s=19",  caption: "Lahıc — daş döşənmiş küçələr" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSQYn9HjHM4mQPEbrxtGxJn6GLqtQcWoOtnSyF1HS0VWEQtnik9If5Wkh6vTesg63sxuAXz0ChDFfVkmTGWpiqUDjU&s=19",  caption: "Tarixi dağ kəndi memarlığı" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTZBYFzz0Fhf9ZPzn0Oi37fxKfMKwB3NEe3lbLmPiL2SiZQnKMOCBzWhKtkeqsSxiUWj7b3_HYaOoXQYJXDD_vHwFg&s=",    caption: "Mis sənətkarlığı emalatxanası" },
    ],
  },
];
