export type LocationType = "farm" | "vineyard" | "beekeeping" | "park" | "lakeside" | "citrus" | "animal" | "cultural" | "tea" | "lavender" | "fish";

export interface Location {
  id: string;
  name: string;
  type: LocationType;
  region: string;
  village: string;
  lat: number;
  lng: number;
  description: string;
  activities: string[];
  products: string[];
  visitInfo: string;
  contact?: string;
  emoji: string;
  color: string;
  photos: { url: string; caption: string }[];
}

export const TYPE_META: Record<LocationType, { label: string; emoji: string; color: string }> = {
  farm:       { label: "Aqroturizm",       emoji: "🌾", color: "#7A8B5C" },
  vineyard:   { label: "Üzümlük",          emoji: "🍇", color: "#9B59B6" },
  beekeeping: { label: "Arıçılıq",         emoji: "🐝", color: "#E8B547" },
  park:       { label: "Milli Park",       emoji: "🌲", color: "#2ECC71" },
  lakeside:   { label: "Göl & Kamp",       emoji: "🏕️", color: "#3498DB" },
  citrus:     { label: "Sitrus Bağı",      emoji: "🍋", color: "#F39C12" },
  animal:     { label: "Heyvan Ferması",   emoji: "🦙", color: "#E74C3C" },
  cultural:   { label: "Kənd Turizmi",    emoji: "🏺", color: "#C0392B" },
  tea:        { label: "Çay Plantasiyası", emoji: "🍵", color: "#27AE60" },
  lavender:   { label: "Lavanda Bağı",     emoji: "💜", color: "#8E44AD" },
  fish:       { label: "Balıqçılıq",       emoji: "🐟", color: "#1A6EA8" },
};

export const LOCATIONS: Location[] = [
  {
    id: "biogarden",
    name: "BioGarden",
    type: "farm",
    region: "Şəki",
    village: "Oryat kəndi",
    lat: 41.182,
    lng: 47.108,
    description: "8 hektarlıq üzvi bağ, 3000 meyvə ağacı, ekzotik quşlar, yerli heyvanlar, arıçılıq, üzvi restoran, süni göllər və üzvi bazar — Şəkinin ən unikal aqroturizm məkanı.",
    activities: ["Meyvə yığımı", "Arıçılıq dərsi", "Üzvi restoran", "Heyvanlarla tanışlıq", "Göldə balıqçılıq", "Üzvi bazar"],
    products: ["Üzvi meyvə", "Yerli bal", "Bostanmeyvəsi", "Nar suyu"],
    visitInfo: "Hər gün 09:00 – 19:00",
    contact: "+994 55 XXX XX XX",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "https://biogardensheki.az/images/flora_fauna.jpg",       caption: "BioGarden — flora və fauna, Oryat kəndi, Şəki" },
      { url: "https://biogardensheki.az/upload/202406183209.jpg",       caption: "Meyvə bağları və yaşıl ərazilər" },
      { url: "https://biogardensheki.az/upload/202406192038.jpg",       caption: "Üzvi bağ — 8 hektar sahə" },
      { url: "https://biogardensheki.az/upload/202406194700.jpg",       caption: "Süni göl və istirahət zonaları" },
      { url: "https://biogardensheki.az/upload/202310235311.jpg",       caption: "Yerli heyvanlar və ekzotik quşlar" },
    ],
  },
  {
    id: "hirkan",
    name: "Hirkan Milli Parkı",
    type: "park",
    region: "Lənkəran / Astara",
    village: "Lənkəran",
    lat: 38.784,
    lng: 48.567,
    description: "Nadir bitki örtüyü, Talış dağları, zəngin vəhşi təbiət. Azərbaycanın cənubunda yerləşən UNESCO miras meşəsi — qisman tropik iqlim və endemik flora.",
    activities: ["Piyada turizm", "Eko-turizm", "Quş müşahidəsi", "Fotoqrafiya"],
    products: ["Şəkər qamışı", "Lotan palması", "Dərman bitkiləri"],
    visitInfo: "Hər gün 08:00 – 18:00",
    emoji: "🌲",
    color: "#2ECC71",
    photos: [
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-3.jpeg",                                             caption: "Hirkan Milli Parkı — sıx meşə örtüyü" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-lankaran-2.jpg",                                     caption: "Hirkan meşəsi, Lənkəran — UNESCO Dünya Mirası" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-travel-azerbaijan-lankaran-natura-astara-1.jpg",     caption: "Talış dağlarının ətəyi — endemik flora" },
      { url: "https://cdn.touryup.com/i/att/480/hirkan-national-park-tour-travel-lankaran-1.jpeg",                             caption: "Piyada turizm marşrutu, Astara" },
    ],
  },
  {
    id: "citrus",
    name: "Sitrus Vadisi",
    type: "citrus",
    region: "Lənkəran",
    village: "İstisu qəsəbəsi",
    lat: 38.808,
    lng: 48.594,
    description: "Lənkəranın münbit subtropik iqlimindəki sitrus bağları — mandarin, limon, portağal. Yerli kəndlilərlə birlikdə yığım təcrübəsi.",
    activities: ["Sitrus yığımı", "Bağ gəzintisi", "Yerli bazar"],
    products: ["Mandarin", "Limon", "Portağal", "Feijoa"],
    visitInfo: "Noyabr – Yanvar (hasat mövsümü)",
    emoji: "🍋",
    color: "#F39C12",
    photos: [
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-tour-azerbaijan.jpg",          caption: "Sitrus Vadisi — Lənkəran subtropik bağları" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-azerbaijan-tour-lankaran.jpg",  caption: "Mandarin bağları — İstisu qəsəbəsi" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-tour-azerbaijan-lankaran.jpg",  caption: "Aqroturizm təcrübəsi — meyvə yığımı" },
      { url: "https://cdn.touryup.com/i/att/480/citrus-valley-lankaran-tour-azerbaijan.jpg",  caption: "Yerli sitrus məhsulları bazarı" },
    ],
  },
  {
    id: "ugur",
    name: "Uğur Aqroturizm",
    type: "farm",
    region: "Masallı",
    village: "Tükla kəndi",
    lat: 39.018,
    lng: 48.674,
    description: "Masallının səfalı kəndlərində ənənəvi kənd həyatı, üzvi ferma məhsulları və yerli mətbəxi ilə tanışlıq.",
    activities: ["Kənd turları", "Üzvi ferma", "Yerli mətbəx dərsi", "Heyvanlarla tanışlıq"],
    products: ["Kənd yumurtası", "Ev pendiri", "Tərəvəz"],
    visitInfo: "Həftə içi 09:00 – 17:00",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "/images/map/ugur/image1.jpg", caption: "Uğur Aqroturizm — Tükla kəndi, Masallı" },
      { url: "/images/map/ugur/image2.jpg", caption: "Üzvi ferma sahəsi" },
      { url: "/images/map/ugur/image3.jpg", caption: "Kənd həyatı — yerli mətbəx" },
    ],
  },
  {
    id: "honey",
    name: "Honey Garden",
    type: "beekeeping",
    region: "Şamaxı",
    village: "Qaladərəsi kəndi",
    lat: 40.658,
    lng: 48.776,
    description: "Şamaxı dağlarında yerli arıçılıq ənənəsi. Bal istehsalı prosesi, arı ailələri ilə tanışlıq və praktik arıçılıq dərsləri.",
    activities: ["Arıçılıq dərsi", "Bal dadımı", "Arı ailəsi müşahidəsi", "Mum şam düzəltmə"],
    products: ["Dağ balı", "Şan balı", "Propolis", "Arı südü"],
    visitInfo: "Aprel – Oktyabr, hər gün 10:00 – 17:00",
    emoji: "🐝",
    color: "#E8B547",
    photos: [
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoc2OyfYUVxauSHbKv_0khFdhpMQfdqujh_g&s",         caption: "Honey Garden — Qaladərəsi kəndi, Şamaxı" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH5vc6JuWZrOtKah-v-RpRH-Qv_hYe-andwux1fuZ8nQ&s", caption: "Şan balı — Şamaxı dağ çiçəklərindən" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZfOda4xgAs5H8WFysBch02elGYw8Q7dbQ16vPiJ5ZoI8ZP7xrBKCpFNk&s", caption: "Arı ailəsi ilə praktik arıçılıq" },
      { url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx4e9pjNxN4fFmKikb-5zBJjmwJLitgIGkhvous4-xDQ&s",  caption: "Yerli bal məhsulları — dequstasiya" },
    ],
  },
  {
    id: "lakeside",
    name: "Lakeside Garden",
    type: "lakeside",
    region: "İsmayıllı",
    village: "Tazakənd kəndi",
    lat: 40.803,
    lng: 48.133,
    description: "Göl kənarında üzvi ferma, kamp sahəsi, kənd həyatı və sakit təbiət. Ailəvi istirahət üçün mükəmməl məkan.",
    activities: ["Kamp", "Balıqçılıq", "Kayak", "Üzvi bağçılıq", "Kənd gəzintisi"],
    products: ["Üzvi tərəvəz", "Meyvə", "Yerli qozlar"],
    visitInfo: "Hər gün 08:00 – 21:00",
    emoji: "🏕️",
    color: "#3498DB",
    photos: [
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/a97c51a1-0c20-41b7-9c9e-6c362120c2b7.jpg", caption: "Lakeside Garden — Tazakənd, İsmayıllı" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/a62bce82-9a73-4035-bf40-68e6482f6fb2.JPG", caption: "Göl kənarı istirahət ərazisi" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/0f97d3f5-2ec9-47fa-8e70-155b2a69ffb0.jpeg", caption: "Kamp sahəsi — üzvi ferma bağçası" },
      { url: "https://azerbaijan.travel/fit752x624/center/pages/3503/cd075042-1a55-48d2-9fbb-dcfed6e06e99.JPG", caption: "Göl mənzərəsi — dağ havası" },
    ],
  },
  {
    id: "meysari",
    name: "Meysari Şərabxanası",
    type: "vineyard",
    region: "Şamaxı",
    village: "Meysari kəndi",
    lat: 40.688,
    lng: 48.622,
    description: "Şamaxı torpağının qədim üzüm sortlarından hazırlanan üzvi şərablar. Üzümlük turları, şərab dadımı və restoran təcrübəsi.",
    activities: ["Üzümlük turu", "Şərab dadımı", "Üzüm yığımı", "Restoran", "Cellar turu"],
    products: ["Üzvi şərab", "Üzüm suyu", "Konyak", "Üzüm sirkəsi"],
    visitInfo: "Çərşənbə – Bazar 10:00 – 19:00",
    contact: "+994 50 XXX XX XX",
    emoji: "🍇",
    color: "#9B59B6",
    photos: [
      { url: "https://meysariwines.az/media/img/winery/winery_1_1.png",  caption: "Meysari Şərabxanası — Şamaxı" },
      { url: "https://meysariwines.az/media/img/winery/winery3_1.png",   caption: "Üzümlük — qədim Şamaxı torpağı" },
      { url: "https://meysariwines.az/media/img/winery/winery_6.png",    caption: "Şərab istehsal prosesi" },
      { url: "https://meysariwines.az/media/img/history/history6_1.png", caption: "Meysari şərab tarixi" },
    ],
  },
  {
    id: "alpaca",
    name: "Şamaxı Alpaka Ferması",
    type: "animal",
    region: "Şamaxı",
    village: "Şamaxı",
    lat: 40.617,
    lng: 48.641,
    description: "Azərbaycanda yeganə alpaka ferması. Ailə turizmi, piknik əraziləri və uşaqlar üçün əyləncəli heyvan tanışlığı.",
    activities: ["Alpaka ilə tanışlıq", "Piknik", "Fotoqrafiya", "Uşaq proqramları", "Heyvan bəsləmə"],
    products: ["Alpaka yunu", "Əl işi məmulatlar"],
    visitInfo: "Həftə sonu 10:00 – 18:00, həftə içi rezervasiya ilə",
    emoji: "🦙",
    color: "#E74C3C",
    photos: [
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/e7/89/6e/main-pasture.jpg?w=1400&h=800&s=1",     caption: "Şamaxı Alpaka Ferması — əsas otlaq sahəsi" },
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/f0/48/49/alpaca-azerbaijan.jpg?w=1100&h=-1&s=1",  caption: "Alpaka Azerbaijan — yaxın tanışlıq" },
      { url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/e7/5d/7a/caption.jpg?w=1400&h=-1&s=1",            caption: "Ailə turizmi — piknik əraziləri" },
    ],
  },
  {
    id: "teafarm",
    name: "Yaşıl Çay Plantasiyası",
    type: "tea",
    region: "Lənkəran",
    village: "Lənkəran",
    lat: 38.750,
    lng: 48.848,
    description: "Azərbaycanın cənub subtropik qurşağında yerləşən çay bağları. Çay yığımı, emal prosesi və yerli aqrar ənənələrlə tanışlıq.",
    activities: ["Çay yığımı", "Emal prosesi izlənməsi", "Çay dadımı", "Plantasiya turu"],
    products: ["Yaşıl çay", "Qara çay", "Çay ekstraktı"],
    visitInfo: "May – Sentyabr 08:00 – 17:00",
    emoji: "🍵",
    color: "#27AE60",
    photos: [
      { url: "/images/map/tea/image1.jpg", caption: "Yaşıl Çay Plantasiyası — Lənkəran" },
      { url: "/images/map/tea/image2.jpg", caption: "Çay kolları — subtropik iqlim" },
      { url: "/images/map/tea/image3.jpg", caption: "Əl ilə çay yığımı mövsümü" },
    ],
  },
  {
    id: "lahij",
    name: "Lahıc Kəndi",
    type: "cultural",
    region: "İsmayıllı",
    village: "Lahıc kəndi",
    lat: 40.847,
    lng: 48.335,
    description: "Qafqazın ən qədim qəsəbələrindən biri. Mis sənətkarlığı, tarixi memarlıq, dağ kəndi atmosferi və ənənəvi əl işləri.",
    activities: ["Mis emalatxanası turu", "Tarixi gəzinti", "Sənətkarlıq dərsi", "Fotoqrafiya"],
    products: ["Mis qab-qacaq", "Ənənəvi silah", "Zınqıllar", "Keramika"],
    visitInfo: "Hər gün 09:00 – 18:00",
    emoji: "🏺",
    color: "#C0392B",
    photos: [
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Lahic_kollaj.jpg/960px-Lahic_kollaj.jpg", caption: "Lahıc kəndi — kollaj, İsmayıllı" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSUIQcrq76yUv33jajNCyODFd8g_q74emRHKOhxGZ_ad_D1Nnh2QqwBBStXLH4qGxMSOVBblag5REap9fb00S08nlw&s=19",  caption: "Lahıc — daş döşənmiş küçələr" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSQYn9HjHM4mQPEbrxtGxJn6GLqtQcWoOtnSyF1HS0VWEQtnik9If5Wkh6vTesg63sxuAXz0ChDFfVkmTGWpiqUDjU&s=19",  caption: "Tarixi dağ kəndi memarlığı" },
      { url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTZBYFzz0Fhf9ZPzn0Oi37fxKfMKwB3NEe3lbLmPiL2SiZQnKMOCBzWhKtkeqsSxiUWj7b3_HYaOoXQYJXDD_vHwFg&s=",    caption: "Mis sənətkarlığı emalatxanası" },
    ],
  },
  {
    id: "essenso_lavender",
    name: "Essenso Lavanda Bağı",
    type: "lavender",
    region: "Qəbələ",
    village: "Qəbələ rayonu",
    lat: 40.995,
    lng: 47.845,
    description: "Azərbaycanda ilk kütləvi lavanda yetişdiriciliyi. Essenso.az tibbi aromatik bitkilər — Lavanda (Angustifolia), Peppermint (Nanə) və Melissa istehsalı ilə məşğul olur. Qəbələ rayonunda 26 hektar lavanda sahəsi yaradılmışdır.",
    activities: ["Lavanda bağı gəzintisi", "Aromatik bitki toplanması", "Efir yağı istehsalı", "Fotoqrafiya"],
    products: ["Lavanda efir yağı", "Qurudulmuş lavanda", "Nanə çayı", "Melissa məhsulları"],
    visitInfo: "May – Avqust (çiçəkləmə mövsümü)",
    contact: "essenso.az",
    emoji: "💜",
    color: "#8E44AD",
    photos: [
      { url: "/images/map/lavender-fields-of-gabala/3d9a9340-4e76-42ee-8d7b-4a7e45d14aeb.jpg", caption: "Essenso Lavanda Bağı — Qəbələ, 26 hektar" },
      { url: "/images/map/lavender-fields-of-gabala/535b9cee-223b-4e8c-b455-3511001c3d7e.jpg", caption: "Lavanda (Angustifolia) tarlaları" },
      { url: "/images/map/lavender-fields-of-gabala/ac0eaea8-6fc2-42ea-8574-13ac803c809d.jpg", caption: "Aromatik bitkilər — Qəbələ dağ ətəyi" },
      { url: "/images/map/lavender-fields-of-gabala/fb1a6a1d-389b-4045-8a47-c777ed5ccf99.jpg", caption: "Çiçəkləmə mövsümü — may-avqust" },
    ],
  },
  {
    id: "lekit_bal_evi",
    name: "Ləkit Bal Evi",
    type: "beekeeping",
    region: "Qax",
    village: "Ləkit kəndi",
    lat: 41.423,
    lng: 46.928,
    description: "Qax rayonunun Ləkit kəndindəki Bal Evi — dağ arıçılığı, yerli bal dadımı və pulsuz ekskursiya ilə ziyarətçilərə açıq olan autentik arı məkanı.",
    activities: ["Pulsuz ekskursiya", "Bal dadımı", "Arıçılıq prosesi müşahidəsi", "Yerli mədəniyyətlə tanışlıq"],
    products: ["Dağ balı", "Şan balı", "Mum", "Propolis"],
    visitInfo: "Ekskursiya ödənişsizdir. Hər gün 09:00 – 18:00",
    contact: "+99455 445 45 40",
    emoji: "🐝",
    color: "#E8B547",
    photos: [
      { url: "/images/map/lekit-bal-evi/346e5d55-f6ed-422c-b2d3-beedd6d40f6e.jpg", caption: "Ləkit Bal Evi — Ləkit kəndi, Qax" },
      { url: "/images/map/lekit-bal-evi/4249970d-c542-49a8-a4ea-8b5d795058ca.jpg", caption: "Dağ arıçılığı — Qax meşəliklərindən bal" },
      { url: "/images/map/lekit-bal-evi/69b0c6ee-d81c-4194-a1a5-1595e2502b20.jpg", caption: "Arı ailələri ilə tanışlıq" },
      { url: "/images/map/lekit-bal-evi/9798db41-e6c5-4b3a-ab2b-235c34b8b5fb.jpg", caption: "Yerli bal məhsulları" },
      { url: "/images/map/lekit-bal-evi/a7754621-1af7-49b4-8154-358e4c88b5ea.jpg", caption: "Pulsuz ekskursiya — Ləkit kəndi" },
    ],
  },
  {
    id: "qax_fish",
    name: "Qax Fish",
    type: "fish",
    region: "Qax",
    village: "Süskənd",
    lat: 41.358,
    lng: 46.895,
    description: "Qax rayonunun Süskənd kəndindəki balıqçılıq mərkəzi — dağ sularında təbii balıq yetişdiriciliyi, canlı balıq dadımı və Qax-ın saf dağ havası ilə istirahət.",
    activities: ["Balıqçılıq", "Canlı balıq dadımı", "Dağ istirahəti", "Ailə pikniki"],
    products: ["Çoban balığı", "Qızılbalıq", "Təbii dağ balığı"],
    visitInfo: "Hər gün 08:00 – 20:00",
    emoji: "🐟",
    color: "#1A6EA8",
    photos: [
      { url: "/images/map/qax-fish/2025-05-09.jpg",    caption: "Qax Fish — Süskənd, Qax rayonu" },
      { url: "/images/map/qax-fish/indir.jpg",          caption: "Dağ çayı balıqçılığı" },
      { url: "/images/map/qax-fish/unnamed (1).jpg",    caption: "Canlı balıq — yerli üsul" },
      { url: "/images/map/qax-fish/unnamed.jpg",        caption: "Qax dağ havası — istirahət" },
    ],
  },
  {
    id: "tofiqoglu_ariciliq",
    name: "Tofiqoğlu Arıçılıq",
    type: "beekeeping",
    region: "Qəbələ",
    village: "Zarağan kəndi",
    lat: 40.958,
    lng: 47.813,
    description: "Qəbələ rayonunun Zarağan kəndindəki Tofiqoğlu Arıçılıq — dağ meşəliklərinin saf havasında yerli arıçılıq ənənəsi, bal istehsalı prosesi ilə tanışlıq.",
    activities: ["Arıçılıq ekskursiyası", "Bal dadımı", "Arı ailəsi müşahidəsi", "Yerli mədəniyyətlə tanışlıq"],
    products: ["Dağ balı", "Şan balı", "Propolis", "Arı südü"],
    visitInfo: "Qəbələ 3600 — Zarağan kəndi. Əvvəlcədən rezervasiya tövsiyə olunur.",
    emoji: "🐝",
    color: "#E8B547",
    photos: [
      { url: "/images/map/tofiqoqlu-ariciliq/images.jpg",     caption: "Tofiqoğlu Arıçılıq — Zarağan, Qəbələ" },
      { url: "/images/map/tofiqoqlu-ariciliq/images (1).jpg", caption: "Arıçılıq prosesi — dağ meşəliyi" },
      { url: "/images/map/tofiqoqlu-ariciliq/images (2).jpg", caption: "Yerli bal məhsulları" },
    ],
  },
  {
    id: "qarabag_aqro",
    name: "Qarabağ Aqro",
    type: "farm",
    region: "Bərdə",
    village: "Mirzalıbəyli kəndi",
    lat: 40.376,
    lng: 47.138,
    description: "Bərdə rayonunun Mirzalıbəyli kəndindəki Qarabağ Aqro təsərrüfatı — Qarabağın münbit torpaqlarında yerli əkinçilik, üzvi məhsullar və kənd həyatı ilə tanışlıq.",
    activities: ["Ferma gəzintisi", "Üzvi məhsul yığımı", "Kənd həyatı", "Təbiət turları"],
    products: ["Taxıl məhsulları", "Tərəvəz", "Meyvə", "Yerli ərzaq"],
    visitInfo: "Həftə içi 09:00 – 17:00, rezervasiya tövsiyə olunur",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "https://scontent.fgyd4-2.fna.fbcdn.net/v/t39.30808-6/491925017_1277373857724489_6747505211046774709_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=127cfc&_nc_ohc=sK9rrRMp4bEQ7kNvwFn-2Kb&_nc_oc=AdoIcL5o-JQlMF4pKOmpzEkb-1PJol7Ch7WuHkXcU-5hg4Z4ABIuvGkHO0o-Th7kpBI&_nc_zt=23&_nc_ht=scontent.fgyd4-2.fna&_nc_gid=6vFzE9R7pUTYVatiLk2X6g&_nc_ss=7b2a8&oh=00_Af4Azvwgan-QlExic1-SxM9JOnIzGENsj7GBKSf-a2K37Q&oe=6A09FB1D", caption: "Qarabağ Aqro — Mirzalıbəyli kəndi, Bərdə" },
      { url: "https://scontent.fgyd21-1.fna.fbcdn.net/v/t39.30808-6/491926811_1277373931057815_2094712275458502178_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=127cfc&_nc_ohc=VGLaE3c_izkQ7kNvwHiD7VT&_nc_oc=AdrTtOt_-7vOpMeGHIHqUQKo5khDhgGzr20NNw2nIB-G2rHBnvquzYTyy51YqI-B704&_nc_zt=23&_nc_ht=scontent.fgyd21-1.fna&_nc_gid=8cdwcdsIfTwTeTPkNJpOpw&_nc_ss=7b2a8&oh=00_Af6F2SZ3LJXrRKM9eTP9-VlHpCJHLdd-2ktSO7anDO5pRQ&oe=6A09FC8C", caption: "Qarabağ Aqro — üzvi ferma sahəsi" },
      { url: "https://scontent.fgyd21-1.fna.fbcdn.net/v/t39.30808-6/493834234_1277373587724516_1572178684713668944_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=127cfc&_nc_ohc=dvlFUTxkwZUQ7kNvwGpqgLg&_nc_oc=AdqcHUunuX_jMCn6Exu1V9smSUYVPJSKBQy2faoiXPl8uptjJyFenZPbjH4Nt8q9lTM&_nc_zt=23&_nc_ht=scontent.fgyd21-1.fna&_nc_gid=Oue71gz4kR2cXENu-3K9NQ&_nc_ss=7b2a8&oh=00_Af6rptm1hcu3gdEpdYXV58hGawra5zBhjijpLkHbEfeIaA&oe=6A09F4CD", caption: "Bərdə rayonu — kənd mənzərəsi" },
      { url: "https://scontent.fgyd21-1.fna.fbcdn.net/v/t39.30808-6/491957532_1277373851057823_5297603454631944342_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=qRfb0CzOSwQQ7kNvwFsrxLG&_nc_oc=AdrPZgR_BJD7SGC6op6WYxaTAZ7LEt6_fXu43WlDwIvcLUqpi9caXVhv0NakUL5rGyU&_nc_zt=23&_nc_ht=scontent.fgyd21-1.fna&_nc_gid=OQFbSxsR8gP7RHPc1AB16A&_nc_ss=7b2a8&oh=00_Af6apR7H-glEdRqSjwIiDA1L5Yrj88Y6__HjfIS8C88SSw&oe=6A09E18A", caption: "Qarabağ Aqro — ferma məhsulları" },
    ],
  },
  {
    id: "shabran_aqro",
    name: "Şabran Aqroturizm Mərkəzi",
    type: "farm",
    region: "Şabran",
    village: "Bakı-Quba yolu yaxınlığı",
    lat: 41.221,
    lng: 48.993,
    description: "Şabran rayonunda, Bakı-Quba magistral yolunun yaxınlığında yerləşən aqroturizm mərkəzi — münbit Şabran torpaqlarında kənd həyatı, üzvi əkinçilik və Xəzər ətrafı landşaft.",
    activities: ["Ferma gəzintisi", "Üzvi əkinçilik", "Kənd turları", "Təbiət istirahəti"],
    products: ["Tərəvəz", "Meyvə", "Yerli ərzaq məhsulları"],
    visitInfo: "Hər gün 09:00 – 18:00",
    emoji: "🌾",
    color: "#7A8B5C",
    photos: [
      { url: "/images/map/shabran/image1.jpg", caption: "Şabran Aqroturizm Mərkəzi — Şabran rayonu" },
      { url: "/images/map/shabran/image2.jpg", caption: "Ferma sahəsi — Bakı-Quba yolu ətrafı" },
      { url: "/images/map/shabran/image3.jpg", caption: "Şabran — aqroturizm landşaftı" },
    ],
  },
];
